version: '2.3'
services:
  lab:
    image: c-fx-15-v1-task1:v1.2.7
    environment:
    - JUPYTER_TOKEN
  nginx:
    ports:
    - 80:80
    depends_on:
    - lab
  docker_router:
    image: c-fx-15-v1-task1-docker_router:v1.2.7
  frontend:
    image: c-fx-15-v1-task1-frontend:v1.2.7
  frontend_rproxy:
    image: c-fx-15-v1-task1-frontend_rproxy:v1.2.7
  llm_client:
    image: c-fx-15-v1-task1-llm_client:v1.2.7
    env_file:
    - /dli/secrets/.env
  assessment:
    environment:
    - JUPYTER_TOKEN
    ports:
    - 8080:8080
  mod:
    command: 'sed -i -e ''s:open("/results/PASSED", "w+"):## secret:g'' /notebooks/frontend/server_app.py

      '
  chatbot:
    image: c-fx-15-v1-task1-chatbot:v1.2.7
