worker_processes auto;
pid /etc/nginx/.nginx.pid;

events {
	worker_connections 768;
}

http {
	sendfile on;
	tcp_nopush on;
	tcp_nodelay on;
	client_max_body_size 0;
	keepalive_timeout 65;
	types_hash_max_size 2048;

	default_type application/octet-stream;

	ssl_protocols TLSv1 TLSv1.1 TLSv1.2; # Dropping SSLv3, ref: POODLE
		ssl_prefer_server_ciphers on;

	access_log /var/log/access.log;
	error_log /var/log/error.log;

	gzip on;
	gzip_disable "msie6";

    map $http_upgrade $connection_upgrade {
        default upgrade;
        ''      '';
    }

	## Sticky sessions per https://github.com/gradio-app/gradio/pull/7935
	upstream gradio-app {
		ip_hash;
		server frontend_rproxy:8091;
	}

	# ## Sticky sessions per https://github.com/gradio-app/gradio/pull/7935
	# upstream gradio-chat {
	# 	ip_hash;
	# 	server chatbot_rproxy:8998;
	# }

	upstream gradio-pass {
		ip_hash;
        server lab:7860; 
	}

	server {

		listen 80 default_server;
		listen [::]:80 default_server;

		location / {
			proxy_pass http://localhost/lab;
			proxy_http_version 1.1;
			proxy_set_header Upgrade $http_upgrade;
			proxy_set_header Connection "upgrade";
			proxy_set_header Host $http_host;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_buffering off;
		}

		location /lab {
			proxy_pass http://lab:8888;
			proxy_http_version 1.1;
			proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
			proxy_set_header Host $http_host;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_buffering off;
		}

		# https://www.gradio.app/guides/running-gradio-on-your-web-server-with-nginx
		location /8090/ {
			proxy_pass http://gradio-app/;
			proxy_http_version 1.1;
			proxy_buffering off;
			proxy_redirect off;
			proxy_read_timeout 3600;
			proxy_send_timeout 3600;

			proxy_set_header Upgrade $http_upgrade;
			proxy_set_header Connection "";

			proxy_set_header Host $http_host;
			proxy_set_header X-Forwarded-Host $http_host;
			proxy_set_header X-Forwarded-Proto $scheme;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_set_header X-Real-IP $remote_addr;
		}

		# # https://www.gradio.app/guides/running-gradio-on-your-web-server-with-nginx
		# location /8999/ {
		# 	proxy_pass http://gradio-chat/;
		# 	proxy_http_version 1.1;
		# 	proxy_buffering off;
		# 	proxy_redirect off;
		# 	proxy_set_header Host $http_host;  # Use $http_host to pass the original Host header
		# 	proxy_set_header X-Real-IP $remote_addr;  # Pass the original client IP
		# 	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;  # Append the client IP to X-Forwarded-For
		# 	proxy_set_header X-Forwarded-Host $host;
		# 	proxy_set_header X-Forwarded-Proto $scheme;
		# 	proxy_set_header Connection "";  # For HTTP/1.1 compatibility
		# 	proxy_set_header Upgrade $http_upgrade;  # For WebSocket support
		# }

		location /7860/ {
			proxy_pass http://gradio-pass/;
			proxy_http_version 1.1;
			proxy_buffering off;
			proxy_redirect off;
			proxy_set_header Host $http_host;  # Use $http_host to pass the original Host header
			proxy_set_header X-Real-IP $remote_addr;  # Pass the original client IP
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;  # Append the client IP to X-Forwarded-For
			proxy_set_header X-Forwarded-Host $host;
			proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Connection $connection_upgrade;
			proxy_set_header Upgrade $http_upgrade;  # For WebSocket support
		}

        location /jaeger {
            proxy_pass http://jaeger:16686; 

            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
        }
	}
}
